name: Auto Pluto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node index.js

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto update playlist'
          push: true
          pull: '--rebase --autostash'
          token: ${{ secrets.GITHUB_TOKEN }}
